include:
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_righ
  - board: seeeduino_xiao_ble
    shield: settings_reset

# there is no settingsreset (needed) for the XIAO
